[package]
name = "toy_trx_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
argh = "0.1"
csv = "1.1"
enum_dispatch = "0.3"
serde = { version = "1", features = ["derive"]}